server:
  port: 80

eureka:
  client:
    register-with-eureka: false #表示向注册中心注册自己 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7001.com:7001/eureka/ #集群版配置

#设置feign 客户端超时时间（ 默认1秒 ，openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后，从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign 日志以什么级别监控哪个接口
    com.halo.springcloud.service.PaymentFeignService: debug
